### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by xxtg666** [xxtg666/xtGitVote#4]
- [x]  防刷票：在vote.html内加载投票列表选项人数时，先创建一个空列表，加载一个用户后将用户名加入此列表，并且在加入用户前判断用户名是否处于列表中，若已经在列表中，则忽略此条comment
- [x] 登录界面同意协议：在点击右上角头像后，弹出一个窗口
- [x] #3 
- [x] 用户黑名单、白名单
- [x] vote.html页面布局优化，显示发起者和管理员操作按钮
- [x] 创建投票权限检查：在打开创建新投票的窗口后，点击提交按钮时先检查是否有权限，不创建无label的issue
- [x] 自动判断投票状态，是否显示结束，隐藏按钮
- [x] please accept our cookie ，点同意后cookie不会随着浏览器关闭清除
- [x] #6
- [ ] 创建投票允许删除最后一项
